export const ENDPOINTS = {
	getEvents: '/events',
	getEventById: (id: number | string) => `/events/${id}`,
	getEventsUserAttending: '/events/user-registered',
	getEventsCreatedByUser: '/events/created-by-user',
	registerToEvent: '/attendee/register',
	createNewEvent: '/events/create/new',
	getUsers: '/users',
	demoteAdmins: (ids: number[]) => `/users/demoteAdmins/${ids}`,
	promoteAdmins: (ids: number[]) => `/users/promoteAdmins/${ids}`,
	getUserInfo: '/users/current/info',
	getAllTags: '/tags',
	authenticate: '/auth/authenticate',
	refreshAccessToken: '/auth/refresh',
	getAllCities: '/addresses/cities',
};
