export enum PAYMENT_STATUS {
    PENDING = 'PENDING',
    PAID = 'PAID',
    FAILED = 'FAILED',
    REFUNDED = 'REFUNDED',
    NOT_REFUNDED = 'NOT_REFUNDED',
    CANCELLED = 'CANCELLED',
    DEFAULT = 'DEFAULT',
}